version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ThingsFinder/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
  db:
    image: postgres
    container_name: thingsfinder-db
    environment:
      POSTGRES_USER: thingsfinder
      POSTGRES_PASSWORD: temporaryPassword
      POSTGRES_DB: thingsDb
    ports:
      - "5432:5432"