version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ThingsFinder/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: thingsfinder
      POSTGRES_PASSWORD: temporaryPassword
      POSTGRES_DB: thingsDb
    ports:
      - "5432:5432"